version: '3'
  services:
    db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: root
      ports:
        - "4306:3306"

    web:
      build: .
      ports:
        - '3000:3000'
      volumes:
        - '.:/freemarket_sample_66a'
      tty: true
      stdin_open: true
      links:
        - db